### ISSUE TITLE
librispeech config problem

### ISSUE THREAD

**Issue by uha22** [didi/athena#28]
Hi,  there are some problems when I try to run the librispeech examples
KeyError: 'subword'. 
Can you update the right config file? Thanks!

**Comment by neneluo** [comment]
Thank you for your attention. We will check it soon.

**Comment by neneluo** [comment]
Hi, sorry for the long waiting, we have been busy in a project recently. I have fixed the bug and pushed to https://github.com/athena-team/athena. Please use the config file https://github.com/athena-team/athena/blob/master/examples/asr/librispeech/transformer.json, and update text_featurizer.py according to https://github.com/athena-team/athena/blob/master/athena/data/text_featurizer.py

**Comment by uha22** [comment]
Thanks!
